export enum ResponseError {
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INVALID_USER_ID = "INVALID_USER_ID",
  INVALID_UPLOAD = "INVALID_UPLOAD",
  INVALID_DATE_RANGE = "INVALID_DATE_RANGE",
  // Gacha
  MACHINE_NOT_FOUND = "MACHINE_NOT_FOUND",
  MACHINE_NOT_AVAILABLE = "MACHINE_NOT_AVAILABLE",
  NO_CARDS_AVAILABLE = "NO_CARDS_AVAILABLE",
  STOCK_CONTENTION = "STOCK_CONTENTION",
  FORCED_CARD_OUT_OF_STOCK = "FORCED_CARD_OUT_OF_STOCK",
  // Solana / wallet
  WALLET_NOT_FOUND = "WALLET_NOT_FOUND",
  INSUFFICIENT_USDC = "INSUFFICIENT_USDC",
  // Sellback
  ROLL_NOT_FOUND = "ROLL_NOT_FOUND",
  ROLL_ALREADY_SOLD_BACK = "ROLL_ALREADY_SOLD_BACK",
  SELLBACK_WINDOW_EXPIRED = "SELLBACK_WINDOW_EXPIRED",
  // Waitlist
  WAITLIST_ENTRY_EXISTS = "WAITLIST_ENTRY_EXISTS",
  WAITLIST_CONTACT_REQUIRED = "WAITLIST_CONTACT_REQUIRED",
  // Referrals
  REFERRAL_WINDOW_EXPIRED = "REFERRAL_WINDOW_EXPIRED",
}
